unit Unit2;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  HWebApp, AppSSI, HtmlTxt, HTTPApp, WapCPAdp, DBWeb, Db, DBTables,
  WapActns, DemoWebModule;

type
  TSessionModule = class(TDataModule)
    WapSession1: TWapSession;
    DefaultAction: TWapAction;
    DemoDelphiSupport: TWapAction;
    procedure DemoDelphiSupportExecute(Sender: TObject;
      Request: THttpRequest; Response: THttpResponse; const Verb,
      Value: String; Params: TVariantList; var Handled: Boolean);
    procedure DefaultActionExecute(Sender: TObject; Request: THttpRequest;
      Response: THttpResponse; const Verb, Value: String;
      Params: TVariantList; var Handled: Boolean);
    procedure SessionModuleCreate(Sender: TObject);
    procedure SessionModuleDestroy(Sender: TObject);
  private
    { Private declarations }
    WebModule: TWebModule1;
    function GetRequest: THttpRequest;
    function GetResponse: THttpResponse;
  public
    { Public declarations }
    property Request: THttpRequest read GetRequest;
    property Response: THttpResponse read GetResponse;
  end;

var
  SessionModule: TSessionModule;

implementation

{$R *.DFM}

procedure TSessionModule.SessionModuleCreate(Sender: TObject);
begin
    // Create the Web Module
    WebModule := TWebModule1(WapSession1.CreateModule(TWebModule1));
end;

procedure TSessionModule.SessionModuleDestroy(Sender: TObject);
begin
    WapSession1.FreeModule(WebModule);
end;

function TSessionModule.GetRequest: THttpRequest;
begin
  Result := WapSession1.Request;
end;

function TSessionModule.GetResponse: THttpResponse;
begin
  Result := WapSession1.Response;
end;

procedure TSessionModule.DemoDelphiSupportExecute(Sender: TObject;
  Request: THttpRequest; Response: THttpResponse; const Verb,
  Value: String; Params: TVariantList; var Handled: Boolean);
begin
    // Output some text
    Writeln(Response.TextOut, '<p>This text was generated by the WebApp action.');
    Writeln(Response.TextOut, '<p>However, this was generated by Delphi 3 WebModules code :');
    Writeln(Response.TextOut, '<br>');
    // Pass control to the WebModule
    WebModule.Execute;
end;

procedure TSessionModule.DefaultActionExecute(Sender: TObject;
  Request: THttpRequest; Response: THttpResponse; const Verb,
  Value: String; Params: TVariantList; var Handled: Boolean);
begin
    with Response do begin
        Writeln(TextOut, 'Click on one the following to demonstrate WebApp''s support for');
        Writeln(TextOut, 'the Delphi 3 WebModules technology:');
        Writeln(TextOut, '<UL>');
        Writeln(TextOut, '<LI><A HREF="' + Request.ScriptName + '/DelphiSupport/TableProducer' + '">TableProducer Demo</A>');
        Writeln(TextOut, '<LI><A HREF="' + Request.ScriptName + '/DelphiSupport/PageProducer' + '">PageProducer Demo</A>');
        Writeln(TextOut, '</UL>');
    end;
end;

end.
